services:
    sonata.admin.jam_type:
        class: Assignment\JamStorageBundle\Admin\JamTypeAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "jam.group.enumerations"
              label: "jam.type.mainlabel"
              label_catalogue: "messages"
        arguments:
            - ~
            - Assignment\JamStorageBundle\Entity\JamType
            - ~

    sonata.admin.year:
        class: Assignment\JamStorageBundle\Admin\YearAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "jam.group.enumerations"
              label: "jam.year.mainlabel"
              label_catalogue: "messages"
        arguments:
            - ~
            - Assignment\JamStorageBundle\Entity\Year
            - ~

    sonata.admin.jam_jar:
        class: Assignment\JamStorageBundle\Admin\JamJarAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "jam.group.jams"
              label: "jam.jar.mainlabel"
              label_catalogue: "messages"
        arguments:
            - ~
            - Assignment\JamStorageBundle\Entity\JamJar
            - ~
        calls:
            - [ setJamJarService, [@jam_jar]]